server:
  port: 9090
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    hikari:
      poolName: Hikari
      maximum-pool-size: 10
      max-lifetime: 1800000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@61.255.47.188:1521/xe
    username: shopping
    password: 1111
mybatis:
  mapper-locations: mybatis/*.xml
  type-aliases-package: com.third.shopping.model


